export enum RoutesEnum {
  COMPANIES = 'clienti',
  COMPANY_LISTS = 'elenco-clienti',
  USERS = 'users',
  UNITS = 'units',
  PROJECTS = 'projects',
  DATA_MANAGEMENT = "data-management",
  RESOURCE_TIMESHEET = 'resource-timesheet',
  UNIT_TIMESHEET = 'unit-timesheet',
  PROFILE = 'profile',
  DETAIL = 'detail',
  NEW = 'nuovo',
  FILTER = 'filter',
  TIMESHEET = "timesheet",
  USER_STATUS = "user-status",
  GANTT = "gantt",
  RESOURCE_GANT_OVERVIEW = "resource-load-overview",
  PROJECTS_GANT_OVERVIEW = "projects-load-overview",
  SKILLS_OVERVIEW = "skills-overview",
  SKILLS = "skills",
  IMPORT_OVERVIEW = "import-overview",
  IMPORT = "import",
  IMPORT_RESOURCES = "import-resources",
  LICENZE = "licenze",
  ELENCO_LICENZE = "elenco-licenze",
  LICENCES = "documenti",
  LISTS  = "elenco"
}
