export enum RoutesEnum {
  MANAGEMENT = 'management',
  USERS = 'users',
  UNITS = 'units',
  RESOURCES = 'resources',
  PROJECTS = 'projects',
  DATA_MANAGEMENT = "data-management",
  RESOURCE_TIMESHEET = 'resource-timesheet',
  UNIT_TIMESHEET = 'unit-timesheet',
  PROFILE = 'profile',
  DETAIL = 'detail',
  NEW = 'new',
  FILTER = 'filter',
  TIMESHEET = "timesheet",
  USER_STATUS = "user-status",
  GANTT = "gantt",
  RESOURCE_GANT_OVERVIEW = "resource-load-overview",
  PROJECTS_GANT_OVERVIEW = "projects-load-overview",
  SKILLS_OVERVIEW = "skills-overview",
  SKILLS = "skills",
  IMPORT_OVERVIEW = "import-overview",
  IMPORT = "import",
  IMPORT_RESOURCES = "import-resources",
  OFFICIAL_TRIGRAMS = "official-trigrams",
  OPERATIONS_TRIGRAMS = "operations-trigrams"
}
